// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAgSvHZVMI1HoOQGcD6DKgAj_Iz8kDk3w',
    appId: '1:920778818629:web:533238b21391ae3bb80f2c',
    messagingSenderId: '920778818629',
    projectId: 'idmall-project',
    authDomain: 'idmall-project.firebaseapp.com',
    storageBucket: 'idmall-project.appspot.com',
    measurementId: 'G-1NK7H04NBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlRUl12A1bA9l90_diwcqR6HpiFGX9LW8',
    appId: '1:920778818629:android:1ddad36c286d41cbb80f2c',
    messagingSenderId: '920778818629',
    projectId: 'idmall-project',
    storageBucket: 'idmall-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmsni2MNeyM0HjMeWr00qy1Qy3yo3KobQ',
    appId: '1:920778818629:ios:b373989517aebaf4b80f2c',
    messagingSenderId: '920778818629',
    projectId: 'idmall-project',
    storageBucket: 'idmall-project.appspot.com',
    iosBundleId: 'com.supercorridor.idmall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmsni2MNeyM0HjMeWr00qy1Qy3yo3KobQ',
    appId: '1:920778818629:ios:826a7c10459d38a7b80f2c',
    messagingSenderId: '920778818629',
    projectId: 'idmall-project',
    storageBucket: 'idmall-project.appspot.com',
    iosBundleId: 'com.supercorridor.idmall.RunnerTests',
  );
}
